language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - sdkmanager tools

install: ./gradlew clean assemble

script:
  - ./gradlew clean :stasis-lib:build :stasis-lib-android:build :stasis-compiler:build

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "uNR3fEDnJfnxFqpGezc5HNfNFnrVO1rj+VRHuc0F1tqEyNo3CXfpA0u0QfFNqQxKkmSWL6uI3kO2Sfb0GB5L0L0LZvVuR6AW8imk4Dv9UN1Nvms8LHdeRhVGoSu3YyPRqSsLTbaUja10xX9P0PfsjHQPjV4jn/KjVJj8soo22/L7cpvj5OEOsQnunZmYpeDDcY1EtoYI1TZwbTXGzNjFJMs7N4/FdBciJJRBD0A5o1v5s9Ei927giJV+1GavUphx/PHnRRCYmf6Mvvz7saY6UL3tytiF6nUwT41xqHrcoUP0tdZNgRhx8NSgdAk2mrd235Ocdp9RKb+846iEmZb0SAzajJuktmDteEIzifNCbUvWHpSl1F6gBV36+NqjEsrgRtrAsJp9UZtquc0ZeH2qufEuWLLvj7kai7G2NU681L/n1oHtBFw/OT9QMS9vlT6gCjl/xDvzFD5vtowYHoFRkrRKt0EB/uUEikcr8+LvItU1qxrSdGc8EnUvklnGJh9HvGEU3kVMHBp3YYJRhaWnKFYGBn1EZGtb6DiTGQA8VoJmqjNxIIW83HHE8LGIUxNKPvJPLc821K+KKxP6jQicE43BNIxenVBxs6okE2XC+TRRXeAeOTfMHPuaJmZVT8jzqqtcRgVijAFg8fNltEpAQ6V4OwF6dSjKpm2BD89Rmw8="
    - secure: "ogqQmZEHRZra/MLzKHCqNj0wwrU16U+WqveK35kmjIjB+LGcX3DWvxevEyQ3GXKPJXg7o4eHgX1hkTMN1xC6Va/t6fUWley1DUNaRlOiQ++OdEKaBMNTbT0C3s+kvqinUzDFp/iHDE+myI3zJ7MKxb6+1xwZkFsfJR2+qLXe6VVaubihRyqV+cDOnjnrg0JCIp0v3aZi0xE0oNs5oOJPcxYME/47Bw/X22mgCjLVTQtyeC9XNwrwO2/pl7uf5fp/y21V2qM1/qeYmGvuJ1L82Hax1hRJeZUw12TWlf+61Z+SGV7yiL3zwxtrOXip+Kd93KP12BduVgYGbqcz0zZEQG8/r1r5IvzeqIhJPLkA4rCsOwTwdHrb88AvTG7mnXIhTeX/tV+dtLPEMizidhVd3f31qIJ81ptawm/2aI5Bjeeo40QhQSwIthHZkL84S4kPunjhrmSP6HpMidnDZ2NmQ4GHkiNd34e73ZoHSVuXjD4ZhxQqM5DhRQYZLssaeahBxNekNO6sy/vX1H9z4nci9MWILf0qHK1HIdcOS99asObuD8SjIEfizd4O7SyujiWuIQE6tqCrVysXr8OzygX4F5kw4ZKW2lvIAyo6SdO9pciE+14Wra5dYIxHBgjMki3wnTg1hhdfFAxU5pV90t1ORRhfblD8IEg5Rv297ixDdVg="

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle